export const TestStock = [
  {
    wool_color_id: 1,
    wool_color_name: "Rojo",
    wool_id: 41,
    wool_ideal_stock: 7,
    wool_price: 3,
    wool_stock: 5,
    wool_thickness_id: 13,
    wool_thickness_name: "Fino",
    wool_type_id: 5,
    wool_type_name: "Ejemplo",
  },
  {
    wool_color_id: 2,
    wool_color_name: "Azul",
    wool_id: 42,
    wool_ideal_stock: 7,
    wool_price: 3,
    wool_stock: 5,
    wool_thickness_id: 13,
    wool_thickness_name: "Fino",
    wool_type_id: 5,
    wool_type_name: "Ejemplo",
  },
  {
    wool_color_id: 3,
    wool_color_name: "Verde",
    wool_id: 43,
    wool_ideal_stock: 7,
    wool_price: 3,
    wool_stock: 5,
    wool_thickness_id: 13,
    wool_thickness_name: "Fino",
    wool_type_id: 5,
    wool_type_name: "Ejemplo",
  },
  {
    wool_color_id: 4,
    wool_color_name: "Amarillo",
    wool_id: 44,
    wool_ideal_stock: 7,
    wool_price: 3,
    wool_stock: 5,
    wool_thickness_id: 13,
    wool_thickness_name: "Fino",
    wool_type_id: 5,
    wool_type_name: "Ejemplo",
  },
  {
    wool_color_id: 5,
    wool_color_name: "Naranja",
    wool_id: 45,
    wool_ideal_stock: 7,
    wool_price: 3,
    wool_stock: 5,
    wool_thickness_id: 13,
    wool_thickness_name: "Fino",
    wool_type_id: 5,
    wool_type_name: "Ejemplo",
  },
  {
    wool_color_id: 6,
    wool_color_name: "Rosa",
    wool_id: 46,
    wool_ideal_stock: 7,
    wool_price: 3,
    wool_stock: 5,
    wool_thickness_id: 13,
    wool_thickness_name: "Fino",
    wool_type_id: 5,
    wool_type_name: "Ejemplo",
  },
  {
    wool_color_id: 7,
    wool_color_name: "Morado",
    wool_id: 47,
    wool_ideal_stock: 7,
    wool_price: 3,
    wool_stock: 5,
    wool_thickness_id: 13,
    wool_thickness_name: "Fino",
    wool_type_id: 5,
    wool_type_name: "Ejemplo",
  },
  {
    wool_color_id: 8,
    wool_color_name: "Blanco",
    wool_id: 48,
    wool_ideal_stock: 7,
    wool_price: 3,
    wool_stock: 5,
    wool_thickness_id: 13,
    wool_thickness_name: "Fino",
    wool_type_id: 5,
    wool_type_name: "Ejemplo",
  },
  {
    wool_color_id: 1,
    wool_color_name: "Rojo",
    wool_id: 41,
    wool_ideal_stock: 7,
    wool_price: 3,
    wool_stock: 5,
    wool_thickness_id: 13,
    wool_thickness_name: "Fino",
    wool_type_id: 5,
    wool_type_name: "Ejemplo",
  },
  {
    wool_color_id: 2,
    wool_color_name: "Azul",
    wool_id: 42,
    wool_ideal_stock: 7,
    wool_price: 3,
    wool_stock: 5,
    wool_thickness_id: 13,
    wool_thickness_name: "Fino",
    wool_type_id: 5,
    wool_type_name: "Ejemplo",
  },
  {
    wool_color_id: 3,
    wool_color_name: "Verde",
    wool_id: 43,
    wool_ideal_stock: 7,
    wool_price: 3,
    wool_stock: 5,
    wool_thickness_id: 13,
    wool_thickness_name: "Fino",
    wool_type_id: 5,
    wool_type_name: "Ejemplo",
  },
  {
    wool_color_id: 4,
    wool_color_name: "Amarillo",
    wool_id: 44,
    wool_ideal_stock: 7,
    wool_price: 3,
    wool_stock: 5,
    wool_thickness_id: 13,
    wool_thickness_name: "Fino",
    wool_type_id: 5,
    wool_type_name: "Ejemplo",
  },
  {
    wool_color_id: 5,
    wool_color_name: "Naranja",
    wool_id: 45,
    wool_ideal_stock: 7,
    wool_price: 3,
    wool_stock: 5,
    wool_thickness_id: 13,
    wool_thickness_name: "Fino",
    wool_type_id: 5,
    wool_type_name: "Ejemplo",
  },
  {
    wool_color_id: 6,
    wool_color_name: "Rosa",
    wool_id: 46,
    wool_ideal_stock: 7,
    wool_price: 3,
    wool_stock: 5,
    wool_thickness_id: 13,
    wool_thickness_name: "Fino",
    wool_type_id: 5,
    wool_type_name: "Ejemplo",
  },
  {
    wool_color_id: 7,
    wool_color_name: "Morado",
    wool_id: 47,
    wool_ideal_stock: 7,
    wool_price: 3,
    wool_stock: 5,
    wool_thickness_id: 13,
    wool_thickness_name: "Fino",
    wool_type_id: 5,
    wool_type_name: "Ejemplo",
  },
  {
    wool_color_id: 8,
    wool_color_name: "Blanco",
    wool_id: 48,
    wool_ideal_stock: 7,
    wool_price: 3,
    wool_stock: 5,
    wool_thickness_id: 13,
    wool_thickness_name: "Fino",
    wool_type_id: 5,
    wool_type_name: "Ejemplo",
  },
  {
    wool_color_id: 1,
    wool_color_name: "Rojo",
    wool_id: 41,
    wool_ideal_stock: 7,
    wool_price: 3,
    wool_stock: 5,
    wool_thickness_id: 13,
    wool_thickness_name: "Fino",
    wool_type_id: 5,
    wool_type_name: "Ejemplo",
  },
  {
    wool_color_id: 2,
    wool_color_name: "Azul",
    wool_id: 42,
    wool_ideal_stock: 7,
    wool_price: 3,
    wool_stock: 5,
    wool_thickness_id: 13,
    wool_thickness_name: "Fino",
    wool_type_id: 5,
    wool_type_name: "Ejemplo",
  },
  {
    wool_color_id: 3,
    wool_color_name: "Verde",
    wool_id: 43,
    wool_ideal_stock: 7,
    wool_price: 3,
    wool_stock: 5,
    wool_thickness_id: 13,
    wool_thickness_name: "Fino",
    wool_type_id: 5,
    wool_type_name: "Ejemplo",
  },
  {
    wool_color_id: 4,
    wool_color_name: "Amarillo",
    wool_id: 44,
    wool_ideal_stock: 7,
    wool_price: 3,
    wool_stock: 5,
    wool_thickness_id: 13,
    wool_thickness_name: "Fino",
    wool_type_id: 5,
    wool_type_name: "Ejemplo",
  },
  {
    wool_color_id: 5,
    wool_color_name: "Naranja",
    wool_id: 45,
    wool_ideal_stock: 7,
    wool_price: 3,
    wool_stock: 5,
    wool_thickness_id: 13,
    wool_thickness_name: "Fino",
    wool_type_id: 5,
    wool_type_name: "Ejemplo",
  },
  {
    wool_color_id: 6,
    wool_color_name: "Rosa",
    wool_id: 46,
    wool_ideal_stock: 7,
    wool_price: 3,
    wool_stock: 5,
    wool_thickness_id: 13,
    wool_thickness_name: "Fino",
    wool_type_id: 5,
    wool_type_name: "Ejemplo",
  },
  {
    wool_color_id: 7,
    wool_color_name: "Morado",
    wool_id: 47,
    wool_ideal_stock: 7,
    wool_price: 3,
    wool_stock: 5,
    wool_thickness_id: 13,
    wool_thickness_name: "Fino",
    wool_type_id: 5,
    wool_type_name: "Ejemplo",
  },
  {
    wool_color_id: 8,
    wool_color_name: "Blanco",
    wool_id: 48,
    wool_ideal_stock: 7,
    wool_price: 3,
    wool_stock: 5,
    wool_thickness_id: 13,
    wool_thickness_name: "Fino",
    wool_type_id: 5,
    wool_type_name: "Ejemplo",
  },
  {
    wool_color_id: 1,
    wool_color_name: "Rojo",
    wool_id: 41,
    wool_ideal_stock: 7,
    wool_price: 3,
    wool_stock: 5,
    wool_thickness_id: 13,
    wool_thickness_name: "Fino",
    wool_type_id: 5,
    wool_type_name: "Ejemplo",
  },
  {
    wool_color_id: 2,
    wool_color_name: "Azul",
    wool_id: 42,
    wool_ideal_stock: 7,
    wool_price: 3,
    wool_stock: 5,
    wool_thickness_id: 13,
    wool_thickness_name: "Fino",
    wool_type_id: 5,
    wool_type_name: "Ejemplo",
  },
  {
    wool_color_id: 3,
    wool_color_name: "Verde",
    wool_id: 43,
    wool_ideal_stock: 7,
    wool_price: 3,
    wool_stock: 5,
    wool_thickness_id: 13,
    wool_thickness_name: "Fino",
    wool_type_id: 5,
    wool_type_name: "Ejemplo",
  },
  {
    wool_color_id: 4,
    wool_color_name: "Amarillo",
    wool_id: 44,
    wool_ideal_stock: 7,
    wool_price: 3,
    wool_stock: 5,
    wool_thickness_id: 13,
    wool_thickness_name: "Fino",
    wool_type_id: 5,
    wool_type_name: "Ejemplo",
  },
  {
    wool_color_id: 5,
    wool_color_name: "Naranja",
    wool_id: 45,
    wool_ideal_stock: 7,
    wool_price: 3,
    wool_stock: 5,
    wool_thickness_id: 13,
    wool_thickness_name: "Fino",
    wool_type_id: 5,
    wool_type_name: "Ejemplo",
  },
  {
    wool_color_id: 6,
    wool_color_name: "Rosa",
    wool_id: 46,
    wool_ideal_stock: 7,
    wool_price: 3,
    wool_stock: 5,
    wool_thickness_id: 13,
    wool_thickness_name: "Fino",
    wool_type_id: 5,
    wool_type_name: "Ejemplo",
  },
  {
    wool_color_id: 7,
    wool_color_name: "Morado",
    wool_id: 47,
    wool_ideal_stock: 7,
    wool_price: 3,
    wool_stock: 5,
    wool_thickness_id: 13,
    wool_thickness_name: "Fino",
    wool_type_id: 5,
    wool_type_name: "Ejemplo",
  },
  {
    wool_color_id: 8,
    wool_color_name: "Blanco",
    wool_id: 48,
    wool_ideal_stock: 7,
    wool_price: 3,
    wool_stock: 5,
    wool_thickness_id: 13,
    wool_thickness_name: "Fino",
    wool_type_id: 5,
    wool_type_name: "Ejemplo",
  },
  {
    wool_color_id: 1,
    wool_color_name: "Rojo",
    wool_id: 41,
    wool_ideal_stock: 7,
    wool_price: 3,
    wool_stock: 5,
    wool_thickness_id: 13,
    wool_thickness_name: "Fino",
    wool_type_id: 5,
    wool_type_name: "Ejemplo",
  },
  {
    wool_color_id: 2,
    wool_color_name: "Azul",
    wool_id: 42,
    wool_ideal_stock: 7,
    wool_price: 3,
    wool_stock: 5,
    wool_thickness_id: 13,
    wool_thickness_name: "Fino",
    wool_type_id: 5,
    wool_type_name: "Ejemplo",
  },
  {
    wool_color_id: 3,
    wool_color_name: "Verde",
    wool_id: 43,
    wool_ideal_stock: 7,
    wool_price: 3,
    wool_stock: 5,
    wool_thickness_id: 13,
    wool_thickness_name: "Fino",
    wool_type_id: 5,
    wool_type_name: "Ejemplo",
  },
  {
    wool_color_id: 4,
    wool_color_name: "Amarillo",
    wool_id: 44,
    wool_ideal_stock: 7,
    wool_price: 3,
    wool_stock: 5,
    wool_thickness_id: 13,
    wool_thickness_name: "Fino",
    wool_type_id: 5,
    wool_type_name: "Ejemplo",
  },
  {
    wool_color_id: 5,
    wool_color_name: "Naranja",
    wool_id: 45,
    wool_ideal_stock: 7,
    wool_price: 3,
    wool_stock: 5,
    wool_thickness_id: 13,
    wool_thickness_name: "Fino",
    wool_type_id: 5,
    wool_type_name: "Ejemplo",
  },
  {
    wool_color_id: 6,
    wool_color_name: "Rosa",
    wool_id: 46,
    wool_ideal_stock: 7,
    wool_price: 3,
    wool_stock: 5,
    wool_thickness_id: 13,
    wool_thickness_name: "Fino",
    wool_type_id: 5,
    wool_type_name: "Ejemplo",
  },
  {
    wool_color_id: 7,
    wool_color_name: "Morado",
    wool_id: 47,
    wool_ideal_stock: 7,
    wool_price: 3,
    wool_stock: 5,
    wool_thickness_id: 13,
    wool_thickness_name: "Fino",
    wool_type_id: 5,
    wool_type_name: "Ejemplo",
  },
  {
    wool_color_id: 8,
    wool_color_name: "Blanco",
    wool_id: 48,
    wool_ideal_stock: 7,
    wool_price: 3,
    wool_stock: 5,
    wool_thickness_id: 13,
    wool_thickness_name: "Fino",
    wool_type_id: 5,
    wool_type_name: "Ejemplo",
  },
];
